apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "otus-chart.fullname" . }}-postgres-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: postgres-init
        image: bitnami/postgresql:15
        env:
        - name: DB_PASSWORD
          value: {{ .Values.postgresql.auth.password | quote }}
        - name: DB_USER
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: PGPASSWORD
          value: {{ .Values.postgresql.auth.password | quote }}
        command:
        - /bin/sh
        - -c
        - |
          sleep 10 && psql -h {{ .Release.Name }}-postgresql -U postgres -d postgres <<EOF
          CREATE TABLE IF NOT EXISTS users (
                id SERIAL PRIMARY KEY,
                username VARCHAR(256) UNIQUE NOT NULL,
                firstName VARCHAR(255),
                lastName VARCHAR(255),
                email VARCHAR(255),
                phone VARCHAR(50),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
          EOF