apiVersion: v1  
kind: Secret  
metadata:  
  name: {{ include "otus-chart.fullname" . }}  
type: Opaque  
data:
  DB_HOST: {{ .Values.secret.DB_HOST | b64enc | quote }}
  DB_NAME: {{ .Values.secret.DB_NAME| b64enc | quote }}
  DB_USER: {{ .Values.secret.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}
  DB_PORT: {{ .Values.secret.DB_PORT | toString | b64enc | quote }}