apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "otus-chart.fullname" . }}-postgres-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: postgres-init
        image: docker.io/bitnami/postgresql:latest
        env:
        - name: DB_PASSWORD
          value: {{ .Values.postgresql.auth.password | quote }}
        - name: DB_USER
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: PGPASSWORD
          value: {{ .Values.postgresql.auth.password | quote }}
        command:
        - /bin/sh
        - -c
        - |
          sleep 10 && psql -h {{ .Release.Name }}-postgresql -U postgres -d userdb <<EOF
          CREATE TABLE IF NOT EXISTS users (
                id SERIAL PRIMARY KEY,
                username VARCHAR(256) UNIQUE NOT NULL,
                firstName VARCHAR(255),
                lastName VARCHAR(255),
                email VARCHAR(255),
                phone VARCHAR(50),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                password_hash VARCHAR(255)
            );
          CREATE TABLE IF NOT EXISTS billing (
            id INTEGER PRIMARY KEY,
            balance DECIMAL(10, 2) DEFAULT 0.00 NOT NULL
            );
          CREATE TABLE IF NOT EXISTS notifications (
                id SERIAL PRIMARY KEY,
                recipient_id INTEGER NOT NULL,
                message TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                is_read BOOLEAN NOT NULL DEFAULT FALSE
            );
          CREATE TABLE  orders (
              id SERIAL PRIMARY KEY,
              price DECIMAL(10, 2) NOT NULL,
              product_name VARCHAR(255) NOT NULL,
              status VARCHAR(20) NOT NULL DEFAULT 'new',
              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
              user_id INTEGER NOT NULL
          );
            GRANT ALL PRIVILEGES ON DATABASE userdb to {{ .Values.postgresql.auth.username | quote }};
            GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{ .Values.postgresql.auth.username | quote }};
            GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO {{ .Values.postgresql.auth.username | quote }};
          EOF